### ISSUE TITLE
Test the CTCast and Python script to make sure they have identical outputs

### ISSUE THREAD

**Issue by romerorisa** [grainger-illinois/CTCast#33]
Maybe also change how the fake server works to accept both the Python script and CTCast at once

**Comment by HanBoyou** [comment]
This could not work as a unit test because it requires multiple applications (scripts) to work together.

**Comment by HanBoyou** [comment]
Updated fake server. Now it takes input from ports 10002 and 10003. we select 10003 as the "comparison group"  which runs the python script. The python script is updated as well.

**Comment by HanBoyou** [comment]
Seems that they are providing same outputs now.
