### ISSUE TITLE
UI update

### ISSUE THREAD

**Issue by HanBoyou** [grainger-illinois/CTCast#53]
![CTCast - Hi-fi](https://user-images.githubusercontent.com/55033157/198717584-1274c310-7779-4866-947e-8da96dd80ff7.png)

**Comment by HanBoyou** [comment]
@shubhamk008 Could you provide the rgb data for the colors?

**Comment by shubhamk008** [comment]
I have given edit access ***@***.*** might be able to click and see the colors now. Let me know how it goes.

Regards,

Shubham Kumar
 

    On Wednesday, 1 February, 2023 at 03:31:11 pm GMT-6, HanBoyou ***@***.***> wrote:  
 
 


@shubhamk008 Could you provide the rgb data for the colors?

**Comment by shubhamk008** [comment]
Hi @HanBoyou, how are we doing with the redesign?

**Comment by HanBoyou** [comment]
You could checkout the branch itself. There has been some progress and currently the problem's at the splitter button.
